apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - name: testapi
        image: magnificent/testapi:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testapi-service
spec:
  selector:
    app: testapi
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080
      nodePort: 30081
  type: NodePort
