name: CI/CD Pipeline for TestApi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: testapi
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: magnificent

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Build and publish app
      - name: Restore and Publish .NET app
        run: |
          dotnet restore TestApi.csproj
          dotnet publish TestApi.csproj -c Release -o out

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./TestApi/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      # Optional: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Kubernetes..."
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
